CREATE DATABASE IF NOT EXISTS coffee;
CREATE DATABASE IF NOT EXISTS account;
GRANT ALL PRIVILEGES ON coffee.*  TO 'root'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON account.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
